CREATE OR REPLACE PROCEDURE MAKE_CUST_VIEW (DATEFROM IN DATE)
IS
BEGIN
	CREATE OR REPLACE VIEW CUST_RANK (CUSTOMER_ID, TOTAL) AS
		SELECT CUSTOMER_ID, SUM(TOTAL) AS TOTAL
		FROM 
			(SELECT (CO.PRICE*B.PURCHASE_QUANTITY) AS TOTAL, C.CUSTOMER_ID AS CUSTOMER_ID
			FROM CUSTOMER C JOIN PURCHASE P ON C.CUSTOMER_ID=P.CUSTOMER_ID JOIN BUYCOFFEE B ON B.PURCHASE_ID = P.PURCHASE_ID JOIN COFFEE CO ON CO.COFFEE_ID = B.COFFEE_ID
			WHERE B.PURCHASE_QUANTITY>0 AND P.PURCHASE_DATE>DATEFROM)
		GROUP BY CUSTOMER_ID
		ORDER BY TOTAL DESC;

END;
/

CREATE OR REPLACE FUNCTION CUSTOMER_SPENT(K IN INT, DATEFROM IN DATE)
RETURN SYS_REFCURSOR
IS
	CUR SYS_REFCURSOR;
BEGIN
	
	MAKE_CUST_VIEW(DATEFROM);
	
	OPEN CUR FOR SELECT CUSTOMER_ID
		FROM
			(SELECT S.CUSTOMER_ID, 1+ (SELECT COUNT(*) FROM CUST_RANK T WHERE T.TOTAL>S.TOTAL) AS RANK
			FROM CUST_RANK S)
		WHERE RANK >= K;
		RETURN CUR;
END;
/