CREATE OR REPLACE FUNCTION CUSTOMER_SPENT(K IN INT)
RETURN SYS_REFCURSOR
IS
	CUR SYS_REFCURSOR;
BEGIN
	
	OPEN CUR FOR SELECT CUSTOMER_ID
		FROM
			(SELECT S.CUSTOMER_ID, 1+ (SELECT COUNT(*) FROM CUST_RANK T WHERE T.TOTAL>S.TOTAL) AS RANK
			FROM CUST_RANK S)
		WHERE RANK >= K;
		RETURN CUR;
END;
/