CREATE OR REPLACE FUNCTION CUSTOMER_SPENT(CUSTID IN INT, DATEFROM IN DATE)
RETURN FLOAT
IS
TOT FLOAT;
BEGIN
SELECT SUM(TOTAL) INTO TOT
FROM
(SELECT (CO.PRICE*B.PURCHASE_QUANTITY) AS TOTAL
FROM CUSTOMER C JOIN PURCHASE P ON C.CUSTOMER_ID=P.CUSTOMER_ID JOIN BUYCOFFEE B ON B.PURCHASE_ID = P.PURCHASE_ID JOIN COFFEE CO ON CO.COFFEE_ID = B.COFFEE_ID
WHERE C.CUSTOMER_ID = CUSTID AND P.PURCHASE_TIME >= DATEFROM);
IF TOT IS NULL THEN
TOT := 0;
END IF;
RETURN TOT;
END;
/

select customer_spent(1, to_date('2003/07/07', 'yyyy/mm/dd')) from dual;